ignored = ["github.com/bitnami-labs/helm-crd/k8s.io/code-generator/vendor*"]

[[constraint]]
  branch = "master"
  name = "github.com/arschles/assert"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.2"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.8.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.8.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "5.0.1"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.9.1"

[prune]
  go-tests = true
  unused-packages = true
